packages:
  - docs

minimumReleaseAge: 1440

overrides:
  defu@<=6.1.4: '>=6.1.5'
  devalue@<5.6.4: '>=5.6.4'
  devalue@<=5.6.3: '>=5.6.4'
  h3@<1.15.6: '>=1.15.6'
  h3@<1.15.9: '>=1.15.9'
  h3@<=1.15.8: '>=1.15.9'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  smol-toml@<1.6.1: '>=1.6.1'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
