// <auto-generated>
// This file was auto-generated by OpenApiCodeGenerator.
// Do not make direct changes to the file.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System;
using System.IO;
using System.Text.Json.Serialization;

namespace Generated.ShowcaseOpenapi;

file interface IOpenApiGeneratedTypeAlias<TSelf, TValue>
    where TSelf : struct, IOpenApiGeneratedTypeAlias<TSelf, TValue>
{
    static abstract TSelf Create(TValue value);

    TValue Value { get; }
}

file sealed class OpenApiGeneratedBinaryStreamJsonConverter : JsonConverter<Stream>
{
    public override Stream? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException("Expected a base64-encoded string for binary content.");
        }

        string? base64 = reader.GetString();
        if (string.IsNullOrEmpty(base64))
        {
            return new MemoryStream();
        }

        try
        {
            byte[] bytes = Convert.FromBase64String(base64);
            return new MemoryStream(bytes, writable: false);
        }
        catch (FormatException exception)
        {
            throw new JsonException("Expected a base64-encoded string for binary content.", exception);
        }
    }

    public override void Write(Utf8JsonWriter writer, Stream? value, JsonSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNullValue();
            return;
        }

        long originalPosition = 0;
        if (value.CanSeek)
        {
            originalPosition = value.Position;
            value.Position = 0;
        }

        try
        {
            using var buffer = new MemoryStream();
            value.CopyTo(buffer);
            writer.WriteStringValue(Convert.ToBase64String(buffer.ToArray()));
        }
        finally
        {
            if (value.CanSeek)
            {
                value.Position = originalPosition;
            }
        }
    }
}

file sealed class OpenApiGeneratedTypeAliasJsonConverter<TAlias, TValue> : JsonConverter<TAlias>
    where TAlias : struct, IOpenApiGeneratedTypeAlias<TAlias, TValue>
{
    public override TAlias Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        TValue value = JsonSerializer.Deserialize<TValue>(ref reader, options)!;
        return TAlias.Create(value);
    }

    public override void Write(Utf8JsonWriter writer, TAlias value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value.Value, options);
    }
}

file sealed class OpenApiGeneratedBinaryStreamTypeAliasJsonConverter<TAlias> : JsonConverter<TAlias>
    where TAlias : struct, IOpenApiGeneratedTypeAlias<TAlias, Stream>
{
    private static readonly OpenApiGeneratedBinaryStreamJsonConverter StreamConverter = new();

    public override TAlias Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        Stream stream = StreamConverter.Read(ref reader, typeof(Stream), options) ?? new MemoryStream();
        return TAlias.Create(stream);
    }

    public override void Write(Utf8JsonWriter writer, TAlias value, JsonSerializerOptions options)
    {
        StreamConverter.Write(writer, value.Value, options);
    }
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Kind
{
    [JsonStringEnumMemberName("invoice")]
    Invoice,
    [JsonStringEnumMemberName("receipt")]
    Receipt,
    [JsonStringEnumMemberName("image")]
    Image
}

/// <summary>
/// Simple string enum.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Status
{
    [JsonStringEnumMemberName("pending")]
    Pending,
    [JsonStringEnumMemberName("sent")]
    Sent,
    [JsonStringEnumMemberName("failed")]
    Failed
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CircleShapeType
{
    [JsonStringEnumMemberName("circle")]
    Circle
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RectangleShapeType
{
    [JsonStringEnumMemberName("rectangle")]
    Rectangle
}

/// <summary>
/// Strongly typed UUID alias.
/// </summary>
/// <summary>
/// Type alias for Guid.
/// </summary>
[JsonConverter(typeof(OpenApiGeneratedTypeAliasJsonConverter<EventId, Guid>))]
public readonly record struct EventId(Guid Value) : IOpenApiGeneratedTypeAlias<EventId, Guid>
{
    public static EventId Create(Guid value) => new(value);
}

/// <summary>
/// Strongly typed timestamp alias.
/// </summary>
/// <summary>
/// Type alias for DateTimeOffset.
/// </summary>
[JsonConverter(typeof(OpenApiGeneratedTypeAliasJsonConverter<EventTimestamp, DateTimeOffset>))]
public readonly record struct EventTimestamp(DateTimeOffset Value) : IOpenApiGeneratedTypeAlias<EventTimestamp, DateTimeOffset>
{
    public static EventTimestamp Create(DateTimeOffset value) => new(value);
}

/// <summary>
/// Strongly typed binary payload alias.
/// </summary>
/// <summary>
/// Type alias for Stream.
/// </summary>
[JsonConverter(typeof(OpenApiGeneratedBinaryStreamTypeAliasJsonConverter<BinaryPayload>))]
public readonly record struct BinaryPayload(Stream Value) : IOpenApiGeneratedTypeAlias<BinaryPayload, Stream>
{
    public static BinaryPayload Create(Stream value) => new(value);
}

/// <summary>
/// Simple string enum.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DeliveryState
{
    [JsonStringEnumMemberName("pending")]
    Pending,
    [JsonStringEnumMemberName("sent")]
    Sent,
    [JsonStringEnumMemberName("failed")]
    Failed
}

/// <summary>
/// Demonstrates additionalProperties extension-data support.
/// </summary>
public record Metadata
{
    [JsonPropertyName("source")]
    public required string Source { get; init; }


    [JsonExtensionData]
    public IReadOnlyDictionary<string, string>? AdditionalProperties { get; init; }
}

/// <summary>
/// Demonstrates direct stream handling and inline enums.
/// </summary>
public record Attachment
{
    [JsonPropertyName("fileName")]
    public required string FileName { get; init; }

    /// <summary>
    /// Direct binary property emitted as Stream.
    /// </summary>
    [JsonPropertyName("content")]
    [JsonConverter(typeof(OpenApiGeneratedBinaryStreamJsonConverter))]
    public required Stream Content { get; init; }

    [JsonPropertyName("kind")]
    public Kind? Kind { get; init; }

}

/// <summary>
/// Base record for allOf inheritance.
/// </summary>
public record DeliveryBase
{
    /// <summary>
    /// Strongly typed UUID alias.
    /// </summary>
    [JsonPropertyName("id")]
    public required EventId Id { get; init; }

    /// <summary>
    /// Strongly typed timestamp alias.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public required EventTimestamp CreatedAt { get; init; }

}

public record DeliveryRecord : DeliveryBase
{
    /// <summary>
    /// Simple string enum.
    /// </summary>
    [JsonPropertyName("status")]
    public required Status Status { get; init; }

    /// <summary>
    /// Strongly typed binary payload alias.
    /// </summary>
    [JsonPropertyName("payload")]
    public required BinaryPayload Payload { get; init; }

    /// <summary>
    /// Demonstrates direct stream handling and inline enums.
    /// </summary>
    [JsonPropertyName("attachment")]
    public Attachment? Attachment { get; init; }

    /// <summary>
    /// Demonstrates additionalProperties extension-data support.
    /// </summary>
    [JsonPropertyName("metadata")]
    public Metadata? Metadata { get; init; }

    [JsonPropertyName("tags")]
    public IReadOnlyList<string>? Tags { get; init; }

    [JsonPropertyName("note")]
    public string? Note { get; init; }

}

public record Circle
{
    [JsonPropertyName("shapeType")]
    public required CircleShapeType ShapeType { get; init; }

    [JsonPropertyName("radius")]
    public required double Radius { get; init; }

}

public record Rectangle
{
    [JsonPropertyName("shapeType")]
    public required RectangleShapeType ShapeType { get; init; }

    [JsonPropertyName("width")]
    public required double Width { get; init; }

    [JsonPropertyName("height")]
    public required double Height { get; init; }

}

[JsonDerivedType(typeof(Circle), "circle")]
[JsonDerivedType(typeof(Rectangle), "rectangle")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "shapeType")]
public abstract record Shape;

public record EmailContact
{
    [JsonPropertyName("email")]
    public required string Email { get; init; }

}

public record WebhookContact
{
    [JsonPropertyName("url")]
    public required Uri Url { get; init; }

}

/// <remarks>
/// Union of: EmailContact | WebhookContact
/// </remarks>
[JsonDerivedType(typeof(EmailContact), "EmailContact")]
[JsonDerivedType(typeof(WebhookContact), "WebhookContact")]
public abstract record ContactMethod;

public record Notification
{
    [JsonPropertyName("record")]
    public required DeliveryRecord Record { get; init; }

    [JsonPropertyName("preferredShape")]
    public required Shape PreferredShape { get; init; }

    [JsonPropertyName("contact")]
    public required ContactMethod Contact { get; init; }

}
